services:
  - type: web
    name: silver-engine
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: '--max-old-space-size=384'
